name       : tk
version    : 8.6.9.1
release    : 10
source     :
    - https://netcologne.dl.sourceforge.net/project/tcl/Tcl/8.6.9/tk8.6.9.1-src.tar.gz : 8fcbcd958a8fd727e279f4cac00971eee2ce271dc741650b1fc33375fb74ebb4
homepage   : https://www.tcl.tk
license    : TCL
component  : programming.library
libsplit   : no
summary    : Tk (GUI toolkit standard for Tcl)
description: |
    TK is a graphical user interface toolkit that is standard for Tcl but also allows application programming in other languages as well, allowing for applications to run on multiple platforms.
builddeps  :
    - pkgconfig(tcl)
    - pkgconfig(x11)
    - pkgconfig(xft)
    - pkgconfig(xscrnsaver)
patterns   :
    - demos :
        - /usr/lib64/tk8.6/demos
    - docs :
        - /usr/share/doc
        - /usr/share/man/mann
        - /usr/share/man/man3
environment: |
    export tkver=${version:0:3}
setup      : |
    pushd unix
        %configure --disable-static \
            --includedir=/usr/include/tk${tkver} \
            --enable-64bit \
            CFLAGS="$CFLAGS -I/usr/include/tcl${tkver}"
    popd
build      : |
    %make -C unix TK_LIBRARY=%libdir%/tk${tkver}
install    : |
    %make_install install-private-headers -C unix TK_LIBRARY=%libdir%/tk${tkver}

    ln -sv /usr/bin/wish${tkver} $installdir/usr/bin/wish
    ln -sv libtk${tkver}.so $installdir%libdir%/libtk.so

    # remove build $workdir traces
    libdir=%libdir%     # stupid hack because the substitution of %libdir% does not work
    sed -e "s|$workdir/unix|$libdir|" -e "s|$workdir|/usr/include/tk${tkver}|" -i $installdir/$libdir/tkConfig.sh
