name       : tk
version    : 8.6.8
release    : 7
source     :
    - https://netcologne.dl.sourceforge.net/project/tcl/Tcl/8.6.8/tk8.6.8-src.tar.gz : 49e7bca08dde95195a27f594f7c850b088be357a7c7096e44e1158c7a5fd7b33
homepage   : https://www.tcl.tk
license    : TCL
component  : programming.library
libsplit   : no
summary    : Tk (GUI toolkit standard for Tcl)
description: |
    TK is a graphical user interface toolkit that is standard for Tcl but also allows application programming in other languages as well, allowing for applications to run on multiple platforms.
builddeps  :
    - pkgconfig(tcl)
    - pkgconfig(x11)
    - pkgconfig(xft)
    - pkgconfig(xscrnsaver)
patterns   :
    - demos:
        - /usr/lib64/tk8.6/demos
    - devel:
        - /usr/lib64/tk*/include/*/*.h
    - docs :
        - /usr/share/doc
        - /usr/share/man/mann
        - /usr/share/man/man3
setup      : |
    pushd unix
        %configure --disable-static \
            --includedir=/usr/include/tk${version%.*} \
            --enable-64bit \
            CFLAGS="$CFLAGS -I/usr/include/tcl${version%.*}"
    popd
build      : |
    %make -C unix TK_LIBRARY=%libdir%/tk${version%.*}
install    : |
    export tv="tk${version%.*}"

    %make_install -C unix TK_LIBRARY=%libdir%/$tv

    # install private headers
    mkdir -p $installdir%libdir%/$tv/include/{generic,unix}
    find generic unix -name "*.h" -exec install '{}' $installdir%libdir%/$tv/include/'{}' ';'

    ln -sv /usr/bin/wish${version%.*} $installdir/usr/bin/wish
    ln -sv lib$tv.so $installdir%libdir%/libtk.so

    # remove build $workdir traces
    libdir=%libdir%     # stupid hack because the substitution of %libdir% does not work
    sed -e "s|$workdir/unix|$libdir|" -e "s|$workdir|$libdir/$tv/include|" -i $installdir/$libdir/tkConfig.sh
