name       : tk
version    : 8.6.6
release    : 4
source     :
    - http://prdownloads.sourceforge.net/tcl/tk8.6.6-src.tar.gz : d62c371a71b4744ed830e3c21d27968c31dba74dd2c45f36b9b071e6d88eb19d
homepage   : http://www.tcl.tk
license    :
    - TCL
summary    : Tk (GUI toolkit standard for Tcl)
builddeps  :
    - pkgconfig(tcl)
    - pkgconfig(x11)
component  : programming.library
libsplit   : no
patterns   :
    - docs:
        - /usr/share/doc
        - /usr/share/man/mann
        - /usr/share/man/man3
        - /usr/lib/tk8.6/demos/
description: |
    TK is a graphical user interface toolkit that is standard for Tcl but also allows application programming in other languages as well, allowing for applications to run on multiple platforms.
setup      : |
    pushd unix
    %configure --disable-static --includedir=/usr/include/tk8.6 --enable-64bit CFLAGS="$CFLAGS -I/usr/include/tcl8.6"
build      : |
    pushd unix
    %make
install    : |
    pushd unix
    %make_install
