name       : tk
version    : 8.6.9
release    : 9
source     :
    - https://netcologne.dl.sourceforge.net/project/tcl/Tcl/8.6.9/tk8.6.9-src.tar.gz : d3f9161e8ba0f107fe8d4df1f6d3a14c30cc3512dfc12a795daa367a27660dac
homepage   : https://www.tcl.tk
license    : TCL
component  : programming.library
libsplit   : no
summary    : Tk (GUI toolkit standard for Tcl)
description: |
    TK is a graphical user interface toolkit that is standard for Tcl but also allows application programming in other languages as well, allowing for applications to run on multiple platforms.
builddeps  :
    - pkgconfig(tcl)
    - pkgconfig(x11)
    - pkgconfig(xft)
    - pkgconfig(xscrnsaver)
patterns   :
    - demos :
        - /usr/lib64/tk8.6/demos
    - docs :
        - /usr/share/doc
        - /usr/share/man/mann
        - /usr/share/man/man3
setup      : |
    pushd unix
        %configure --disable-static \
            --includedir=/usr/include/tk${version%.*} \
            --enable-64bit \
            CFLAGS="$CFLAGS -I/usr/include/tcl${version%.*}"
    popd
build      : |
    %make -C unix TK_LIBRARY=%libdir%/tk${version%.*}
install    : |
    export tv="tk${version%.*}"

    %make_install install-private-headers -C unix TK_LIBRARY=%libdir%/$tv

    ln -sv /usr/bin/wish${version%.*} $installdir/usr/bin/wish
    ln -sv lib$tv.so $installdir%libdir%/libtk.so

    # remove build $workdir traces
    libdir=%libdir%     # stupid hack because the substitution of %libdir% does not work
    sed -e "s|$workdir/unix|$libdir|" -e "s|$workdir|/usr/include/$tv|" -i $installdir/$libdir/tkConfig.sh
